apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-gcp-gridgain9-display
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: GridGain9 Terraform Module for GCP
    source:
      repo: https://github.com/gridgain/terraform-gcp-gridgain9.git
      sourceType: git
  ui:
    input:
      variables:
        enable_disk_encryption:
          name: enable_disk_encryption
          title: Enable Disk Encryption
          tooltip: Whether to enable CMEK disk encryption for the cluster.
        enable_logging:
          name: enable_logging
          title: Enable Logging
          tooltip: Cloud Logging allows you to store, search, analyze, monitor, and alert on log data and events. <a href="https://cloud.google.com/logging/">Learn more</a>
          section: google_cloud_operations
        enable_monitoring:
          name: enable_monitoring
          title: Enable Monitoring
          tooltip: Cloud Monitoring provides visibility into the performance, uptime, and overall health of cloud-powered applications. <a href="https://cloud.google.com/monitoring/">Learn more</a>
          section: google_cloud_operations
        enable_oslogin:
          name: enable_oslogin
          title: Enable Oslogin
          tooltip: Enable OS Login to manage SSH access via IAM roles.
        enable_project_oslogin:
          name: enable_project_oslogin
          title: Enable Project Oslogin
          tooltip: Enforce project-level OS Login instead of instance-level settings.
        goog_cm_deployment_name:
          name: goog_cm_deployment_name
          title: Goog Cm Deployment Name
          tooltip: Internal deployment name assigned by Google Cloud Marketplace.
        gridgain_cluster_dns:
          name: gridgain_cluster_dns
          title: Gridgain Cluster Dns
          tooltip: DNS name assigned to the GridGain cluster.
        gridgain_config:
          name: gridgain_config
          title: Gridgain Config
          tooltip: Content of the GridGain configuration file.
        gridgain_license:
          name: gridgain_license
          title: Gridgain License
          tooltip: Content of the GridGain license file.
        gridgain_logging_config:
          name: gridgain_logging_config
          title: Gridgain Logging Config
          tooltip: Logging configuration for GridGain nodes.
        gridgain_ssl_cert:
          name: gridgain_ssl_cert
          title: Gridgain SSL Cert
          tooltip: SSL certificate for securing GridGain client and node connections.
        gridgain_ssl_enable:
          name: gridgain_ssl_enable
          title: Gridgain SSL Enable
          tooltip: Enable SSL/TLS encryption for GridGain communication.
        gridgain_ssl_key:
          name: gridgain_ssl_key
          title: Gridgain SSL Key
          tooltip: Private key for the GridGain SSL certificate.
        keystore_password:
          name: keystore_password
          title: Keystore Password
          tooltip: Password to unlock the keystore containing SSL certificates.
        kms_crypto_key_id:
          name: kms_crypto_key_id
          title: Kms Crypto Key Id
          tooltip: ID of the KMS CryptoKey to use for disk encryption.
        kms_key_ring_id:
          name: kms_key_ring_id
          title: Kms Key Ring Id
          tooltip: ID of the KMS key ring that stores the encryption key.
        kms_location:
          name: kms_location
          title: Kms Location
          tooltip: Region of the KMS key ring for encryption keys.
        machine_type:
          name: machine_type
          title: Machine Type
          tooltip: Compute Engine machine type for GridGain nodes.
          xGoogleProperty:
            type: ET_GCE_MACHINE_TYPE
        name_prefix:
          name: name_prefix
          title: Name Prefix
          tooltip: Prefix to use for naming all created resources.
        nodes_count:
          name: nodes_count
          title: Nodes Count
          tooltip: Number of GridGain nodes to deploy in the cluster.
        oslogin_access_principals:
          name: oslogin_access_principals
          title: Oslogin Access Principals
          tooltip: IAM principals that should be granted OS Login access.
        project_id:
          name: project_id
          title: Project Id
          invisible: true
          tooltip: Google Cloud project ID where the deployment will be created.
        public_access_enable:
          name: public_access_enable
          title: Public Access Enable
          tooltip: Allow external public access to the cluster endpoints.
        public_allowlist:
          name: public_allowlist
          title: Public Allowlist
          tooltip: CIDR ranges allowed to access the cluster if public access is enabled.
        region:
          name: region
          title: Region
          tooltip: Google Cloud region where the resources will be deployed.
        root_disk_iops:
          name: root_disk_iops
          title: Root Disk Iops
          tooltip: Custom IOPS configuration for root disks (if supported by disk type).
        root_disk_size_gb:
          name: root_disk_size_gb
          title: Root Disk Size Gb
          tooltip: Size of the root disk in GB.
          xGoogleProperty:
            type: ET_GCE_DISK_SIZE
        root_disk_throughput:
          name: root_disk_throughput
          title: Root Disk Throughput
          tooltip: Custom throughput setting for root disks (if supported by disk type).
        root_disk_type:
          name: root_disk_type
          title: Root Disk Type
          tooltip: Disk type for the VM root disk (e.g. pd-ssd, pd-balanced).
          xGoogleProperty:
            type: ET_GCE_DISK_TYPE
            zoneProperty: zone
        source_image:
          name: source_image
          title: Source Image
          tooltip: Boot disk image to use for the VM (e.g. Ubuntu, Debian, custom image).
          xGoogleProperty:
            type: ET_GCE_DISK_IMAGE
        ssh_pub_key:
          name: ssh_pub_key
          title: SSH Pub Key
          tooltip: Public SSH key for accessing the VM instances.
        subnet_cidr:
          name: subnet_cidr
          title: Subnet Cidr
          tooltip: CIDR range for the subnet where cluster nodes will be deployed.
        subnet_id:
          name: subnet_id
          title: Subnet Id
          tooltip: Subnetwork ID to use for the cluster deployment.
          maxItems: 1
          section: networking
          xGoogleProperty:
            type: ET_GCE_SUBNETWORK
            zoneProperty: zone
            gceSubnetwork:
              networkVariable: networks
        vpc_id:
          name: vpc_id
          title: VPC Name
          tooltip: VPC network to use for the cluster deployment.
          maxItems: 1
          section: networking
          xGoogleProperty:
            type: ET_GCE_NETWORK
            gceNetwork:
              allowSharedVpcs: true
              machineTypeVariable: machine_type
        zones:
          name: zones
          title: Zones
          tooltip: List of zones where GridGain nodes will be deployed.
          minItems: 1
          maxItems: 8
          xGoogleProperty:
            type: ET_GCE_ZONE
      sections:
        - name: networking
          title: Networking
        - name: google_cloud_operations
          title: Google Cloud Operations
          subtext: Monitoring and management for services, containers, applications, and infrastructure
    runtime:
      suggestedActions:
        - heading: Access the instance using gcloud
          description: "Use the following gcloud command to SSH into the instance: `gcloud compute ssh <instance-name> --tunnel-through-iap --zone <zone> --project <project>`"
